title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 

url: https://pages-themes.github.io/cayman/

aux_links:
  Template Repository: https://github.com/pages-themes/cayman
